create table if not exists competitions (
  id bigint generated by default as identity primary key,
  external_id text unique,
  name text not null,
  country text,
  code text,
  created_at timestamptz default now()
);

create table if not exists teams (
  id bigint generated by default as identity primary key,
  external_id text,
  name text not null,
  country text,
  competition_id bigint references competitions(id),
  elo numeric default 1500,
  created_at timestamptz default now(),
  unique(external_id, competition_id)
);

create table if not exists matches (
  id bigint generated by default as identity primary key,
  external_id text unique,
  competition_id bigint references competitions(id),
  utc_date timestamptz not null,
  status text,
  home_team_id bigint references teams(id),
  away_team_id bigint references teams(id),
  home_goals integer,
  away_goals integer,
  created_at timestamptz default now()
);

create table if not exists predictions (
  id bigint generated by default as identity primary key,
  match_id bigint references matches(id),
  model_version text not null,
  market text not null,
  selection text not null,
  probability numeric not null,
  confidence numeric,
  fair_odds numeric,
  market_odds numeric,
  expected_value numeric,
  created_at timestamptz default now()
);

create table if not exists prediction_results (
  id bigint generated by default as identity primary key,
  prediction_id bigint unique references predictions(id),
  won boolean,
  profit numeric,
  roi numeric,
  settled_at timestamptz default now()
);

create index if not exists idx_matches_date on matches(utc_date);
create index if not exists idx_predictions_match on predictions(match_id);
